<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/style-menu.css");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/RideAdd.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/PassengerAdd.js","text/javascript");?>
<style type="text/css">
#map-canvas {
	height: 600px
}
</style>
<div style="margin:10px;">
<div id="cssmenu" style="width: 10%; float: left;">
       <ul>
<!--             <li><a href='#'><span>Inicio</span></a> -->
            <li><a href='#'><span>Carreras</span></a>
            <ul>
                <li style="background: #83ACFF;">
                    <a href="/admin/Ride/add" id="create-ride">Nuevo</a>
                </li>
                <li style="background: #FFA347;"><a href="/admin/Ride/notassigned">No Asignada</a></li>
                <li style="background: #FF94B8;"><a href='#'>En Espera</a></li>
                <li style="background: #75FF75;"><a href="/admin/Ride/ongoing">En Curso</a></li>
            </ul>
            </li>

            <li><a href='#'><span>Pasajeros</span></a>
            <ul>
                <li style="background: #E5FFE5;"><a id="create-passenger" href="/admin/Passenger/add">Nuevo</a></li>
                <li style="background: #E5FFE5;"><a id="search-passenger" href="/admin/Passenger/search">Buscar</a></li>
            </ul>
            </li>

            <li><a href='#'><span>Taxis</span></a>
            <ul>
                <li style="background: #83ACFF;"><a href="/admin/Taxi/withoutcareer">Sin Carrera</a></li>
                <li style="background: #75FF75;"><a href="/admin/Taxi/ongoing">En Curso</a></li>
                <li style="background: #FFFF66;"><a href="/admin/Taxi/off">Apagados</a></li>
                <li style="background: #9999FF;"><a href="/admin/Taxi">Alta/Baja</a></li>
            </ul>
            </li>
        </ul>
    </div>

    <div id="map-canvas" style=" width: 90%; right: 0px;">
</div>
    <div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<!-- <script type="text/javascript" -->
<!-- 	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true"> -->
<!-- </script> -->

<script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true">
</script>
<p id="demo"></p>

<script type="text/javascript">
	$(document).ready(function() {
		 $('#cssmenu > ul > li:has(ul)').addClass("has-sub");

		  $('#cssmenu > ul > li > a').click(function() {
		    var checkElement = $(this).next();

		    $('#cssmenu li').removeClass('active');
		    $(this).closest('li').addClass('active');


		    if((checkElement.is('ul')) && (checkElement.is(':visible'))) {
		      $(this).closest('li').removeClass('active');
		      checkElement.slideUp('normal');
		    }

		    if((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
		      $('#cssmenu ul ul:visible').slideUp('normal');
		      checkElement.slideDown('normal');
		    }

		    if (checkElement.is('ul')) {
		      return false;
		    } else {
		      return true;
		    }
		  });

	var ride = new com.em.RideAdd();

	// network
	ride.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'ds-ride-entries'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>',
		toAutocompleteLabel : '<?php echo $this->url(array('action'=>'autocomplete-label'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nota'); ?>',
		'<?php echo $this->translate('Descripcion'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	//ride.setHeaders(headers);
	// configuration of widgets
	ride.configureTable('#tblRide', true);

	// CRUD
	ride.clickToAdd('#create-ride');
	ride.clickToUpdate('#tblRide a[id^=update-ride-]');
	ride.clickToDelete('#delete-ride');
	//ride.configureAuto('input#nameFilter');
	ride.configureLabelAuto('input#label');

	//----------------------------------------PASSENGER------------------------------------------
	var passenger = new com.em.PassengerAdd();

	// network
	passenger.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>',
		toAutocompleteLabel : '<?php echo $this->url(array('action'=>'autocomplete-label'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre'); ?>',
		'<?php echo $this->translate('Descripcion'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	passenger.setHeaders(headers);
	// configuration of widgets
	passenger.configureTable('#tblPassenger', true);

	// CRUD
	passenger.clickToAdd('#create-passenger');
	passenger.clickToUpdate('#tblPassenger a[id^=update-passenger-]');
	passenger.clickToDelete('#delete-passenger');
	passenger.configureAuto('input#nameFilter');
	passenger.configureLabelAuto('input#label');

	passenger.clickToSearch('#search-passenger');
});

	var flightPath;
    var map;

    function initialize() {
        count = 0;
        var mapOptions = {center: new google.maps.LatLng(-17.760458, -63.131776), zoom: 15};
        map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        //setMarkers(map, beaches);
//        addLine();
//        addpuntoalmapa();

		var myVar = setInterval(function(){myTimer()},1000);
        var painter = setInterval(function(){paintTimer()},3000);
    }
     var count;
	function myTimer() {
		var d = new Date();
		var t = d.toLocaleTimeString();
		document.getElementById('demo').innerHTML = t;
	}

	function paintTimer() {
		count++;
		this.id = '#'+count;
		$(this.id).click();
	}

    //dibuja lineas DES DE AKI
    var flightPlanCoordinates = [
        new google.maps.LatLng(-17.760458, -63.139776),
        new google.maps.LatLng(-17.764666, -63.191555)
    ];
    flightPath = new google.maps.Polyline({
        path: flightPlanCoordinates,
        strokeColor: '#FF0000',
        strokeOpacity: 1.0,
        strokeWeight: 2
    });
    function addLine() {
        flightPath.setMap(map);
    }
    /*Remueve todas las lineas de flightPath*/
    function removeLine() {
        flightPath.setMap(null);
    }
    function asignar(out) {
        removeLine();
        flightPath = new google.maps.Polyline({
            path: out,
            strokeColor: '#FF0000',
            strokeOpacity: 1.0,
            strokeWeight: 2
        });
        addLine();
//        poly = new google.maps.Polyline(flightPath);
//        poly.setMap(map);
    }
    ///////////////////////////////////////////////
    //Create a meausure object to store our markers, MVCArrays, lines and polygons
    var measure = {
        mvcLine: new google.maps.MVCArray(),
        mvcPolygon: new google.maps.MVCArray(),
        mvcMarkers: new google.maps.MVCArray(),
        line: null,
        polygon: null
    };
    var markerini;
    var markerfin;


    ////////////////////////////////////////////////
    google.maps.event.addDomListener(window, 'load', initialize);



    function dibujarruta(id) {
        var ig = id;
        var ur = '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Index', 'action'=>'draw'));?>';

        $.ajax({
            url: ur,
            type: "POST",
			dataType: 'json',
			data: {'taxiId' : 1},
            success: function(data, textStatus, XMLHttpRequest) {
                if (data !== null) {
                    var out = new Array();
                    var i = 0;
                    $(data).each(function() {
                        for (var i = 0; i < data.length; i++)
                        {
                            var item = data[i];
                            out[i] = new google.maps.LatLng(parseFloat(item.latitud), parseFloat(item.longitud));
                        }
                    });
//                    asignar(out);




                    var myLatlng = new google.maps.LatLng(-17.801260,-63.118800);
                    var mapOptions = {
                      zoom: 4,
                      center: myLatlng
                    }


                    var marker = new google.maps.Marker({
                        title: "fdaf",
                        position: myLatlng,
                        map: map,
                        icon: new google.maps.MarkerImage("img/hometaxi.png", new google.maps.Size(32, 40), new google.maps.Point(0, 0), new google.maps.Point(5, 5))
                    });
                }
            },
            error: function(data) {
                alert('error');
            }
        });

    }


    function drawTaxi(id) {
        var ig = id;
        var ur = '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Index', 'action'=>'draw-taxis'));?>';

        $.ajax({
            url: ur,
            type: "POST",
			dataType: 'json',
			data: {'taxiId' : 1},
            success: function(data, textStatus, XMLHttpRequest) {
                if (data !== null) {
                    var out = new Array();
                    var i = 0;
                    $(data).each(function() {
                        for (var i = 0; i < data.length; i++) {
                            var item = data[i];
                            out[i] = new google.maps.LatLng(parseFloat(item.latitud), parseFloat(item.longitud));


                            var myLatlng = new google.maps.LatLng(parseFloat(item.latitud), parseFloat(item.longitud));

                            var marker = new google.maps.Marker({
                                title: "fdaf",
                                position: myLatlng,
                                map: map,
                                icon: new google.maps.MarkerImage("img/hometaxi.png", new google.maps.Size(32, 40), new google.maps.Point(0, 0), new google.maps.Point(5, 5))
                            });
                        }
                    });
//                    asignar(out);




//                     var myLatlng = new google.maps.LatLng(-17.801260,-63.118800);
//                     var mapOptions = {
//                       zoom: 4,
//                       center: myLatlng
//                     }


//                     var marker = new google.maps.Marker({
//                         title: "fdaf",
//                         position: myLatlng,
//                         map: map,
//                         icon: new google.maps.MarkerImage("img/hometaxi.png", new google.maps.Size(32, 40), new google.maps.Point(0, 0), new google.maps.Point(5, 5))
//                     });
                }
            },
            error: function(data) {
                alert('error');
            }
        });

    }
</script>