<form id="<?php echo $this->element->getAttrib('id')?>" action="<?php echo $this->element->getAction()?>" method="post" enctype="multipart/form-data">
<?php echo $this->element->getElement('driverId')->render()?>
<?php echo $this->element->getElement('taxiId')->render()?>
	<div class="row">

	</div>
	<table>
		<tbody>
            <tr class="odd">
                <td></td>
				<td>
    				<div class="span7">
                        <label><?php echo _('Fotografia')?></label>
                        <div class="well" id="pictureDriver" style="width: 127px; height: 127px;">
        				<img src="<?php echo $this->element->getSource()?>" id="profile_img" style="width: 127px; height: 127px;"/>
                        </div>
                    </div>
				</td>
				<td></td>
				<td>
    				<div class="span8">
                        <label><?php echo _('Fotografia')?></label>
                        <div class="well" id="pictureTaxi" style="width: 127px; height: 127px;">
                        <img src="<?php echo $this->element->getSourceTaxi()?>" id="profile_taxi_img" style="width: 127px; height: 127px;"/>
                        </div>
                    </div>
                </td>
			</tr>
			<tr class="odd">
				<td><label><?php echo _('Fotografia') ?></label></td>
				<td>
					<input id="MAX_FILE_SIZE" type="hidden" value="8388608" name="MAX_FILE_SIZE">
					<input type="file" id="file-input-driver" name="filedriver" class="valid">
				</td>
				<td><label><?php echo _('Fotografia del Movil') ?></label></td>
				<td>
					<input id="MAX_FILE_SIZE" type="hidden" value="8388608" name="MAX_FILE_SIZE">
					<input type="file" id="file-input-taxi" name="filetaxi" class="valid">
				</td>
			</tr>
			<tr class="even">
				<td><?php echo $this->element->getElement('firstName')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('firstName')->renderViewHelper()?></td>
				<td><?php echo $this->element->getElement('number')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('number')->renderViewHelper()?></td>
			</tr>
			<tr class="odd">
                <td><?php echo $this->element->getElement('lastName')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('lastName')->renderViewHelper()?></td>
				<td><?php echo $this->element->getElement('phone')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('phone')->renderViewHelper()?></td>
			</tr>
			<tr class="even">
                <td><?php echo $this->element->getElement('ci')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('ci')->renderViewHelper()?></td>
				<td><?php echo $this->element->getElement('mark')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('mark')->renderViewHelper()?></td>
			</tr>
			<tr class="odd">
                <td><?php echo $this->element->getElement('address')->renderLabel()?></td>
                <td><?php echo $this->element->getElement('address')->renderViewHelper()?></td>
				<td><?php echo $this->element->getElement('plaque')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('plaque')->renderViewHelper()?></td>
			</tr>
			<tr class="even">
                <td></td>
                <td></td>
				<td><?php echo $this->element->getElement('typeMark')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('typeMark')->renderViewHelper()?></td>
			</tr>
			<tr class="even">
                <td></td>
                <td></td>
				<td><?php echo $this->element->getElement('model')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('model')->renderViewHelper()?></td>
			</tr>
			<tr class="odd">
                <td><?php
                    if ($this->element->getShowActive()) {
                        echo $this->element->getElement('active')->renderLabel();
                    }
                ?></td>
                <td><?php
                    if ($this->element->getShowActive()) {
                        echo $this->element->getElement('active')->renderViewHelper();
                    }
                ?></td>
				<td><?php echo $this->element->getElement('color')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('color')->renderViewHelper()?></td>
			</tr>
		</tbody>
	</table>
</form>