<div class="top-meta" style="z-index:2;">
	<div class="tabs modules" id="moduleMenu">
		<ul>
			<li></li>
			<li class="shortcut">
				<a href="javascript: (function() {$('#shortcuts').css('display','');})()" class="shortcut">
					<span class="left shortcut"></span>
					<span class="center shortcut"></span>
					<span class="right shortcut"></span>
				</a>
			</li>
		</ul>
	</div>
	<div class="clear"></div>
	<!-- Hidden drawer for the shotcuts. -->
	<div id="shortcuts" style="display: none;" class="noprint" >
		<a class="shortcut active" href="javascript: (function() {$('#shortcuts').css('display','none');})()"></a>
		<ul class="nobullets">
			<li></li>
			<li class="logout">
					<a href="<?php echo $this->url(array('action'=>'logout', 'controller'=>'Auth', 'module'=>'user')); ?>">
					<span class="left"></span>
					<?php echo _('Salir')?>
					<span class="right"></span>
				</a>
			</li>
		</ul>
	</div>

</div>
<div class="bottom-meta noprint" style="z-index:1;">
	<ul class="appMenu functionMenu" id="functionMenuLeft" style="list-style-type: none; list-style-position: initial; list-style-image: initial;">
		<?php
		$firstGroup = $this->navigation()->getContainer(); ?>
		<?php $menus = $firstGroup->getPages(); ?>
		<?php foreach ($menus as $menu) : echo $this->type?>
			<li class="<?php echo $menu->isActive() ? "active" : ''; ?>">
				<a href="<?php echo $menu->getHref();?>"><span><?php echo $this->translate($menu->getLabel()); ?></span></a>
			</li>
		<?php endforeach; ?>
	</ul>
	<div class="clear"></div>
</div>