<?php echo $this->doctype();?>
<html lang="es">
	<head>
        <title><?php echo _('TAXI DIRECTOR')?></title>
		<?php
			$this->headLink()->appendStylesheet("/css/screen.css");
// 			$this->headLink()->appendStylesheet("/css/print.css", "print");
			$this->headLink()->appendStylesheet("/css/dialog.css");
			$this->headLink()->appendStylesheet("/css/input.css");
			$this->headLink()->appendStylesheet("/css/infopanel.css");
			$this->headLink()->appendStylesheet("/css/menu_new.css");
			$this->headLink()->appendStylesheet("/css/tabs_new.css");
			$this->headLink()->appendStylesheet("/css/new_form.css");
			$this->headLink()->appendStylesheet("/css/navigation.css");
			$this->headLink()->appendStylesheet("/css/form2.0.css");


			$this->headLink()->appendStylesheet("/css/zebralistmenu.css");
// 			$this->headLink()->appendStylesheet("/css/siteapp.css");
// // 			//flash messages
			$this->headLink()->appendStylesheet("/css/flashnotification.css");
		?>

		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>

		<div id="footer" class="noprint">
            <a href="<?php echo $this->url(array('action'=>'logout', 'controller'=>'Auth', 'module'=>'user')); ?>">
                <span class="left"></span>
                <?php echo _('Salir')?>
                <span class="right"></span>
            </a>
		</div>
      	<?php echo $this->flashMessages();?>
	</body>
</html>