<?php echo $this->doctype();?>
<html>
	<head>
        <title>ADM MOB</title>
		<?php
			$this->headLink()->appendStylesheet("/css/jscal2.css");
			$this->headLink()->appendStylesheet("/css/zebralist.css");
			$this->headLink()->appendStylesheet("/css/screen.css");
			$this->headLink()->appendStylesheet("/css/print.css", "print");
			$this->headLink()->appendStylesheet("/css/dialog.css");
			$this->headLink()->appendStylesheet("/css/input.css");
			$this->headLink()->appendStylesheet("/css/infopanel.css");
			$this->headLink()->appendStylesheet("/css/menu_new.css");
			$this->headLink()->appendStylesheet("/css/tabs_new.css");
			$this->headLink()->appendStylesheet("/css/new_form.css");
			$this->headLink()->appendStylesheet("/css/navigation.css");
			$this->headLink()->appendStylesheet("/css/form2.0.css");
			$this->headLink()->appendStylesheet("/css/siteapp.css");
// 			//flash messages
// 			$this->headLink()->appendStylesheet("/css/flashnotification.css");
//
//			$this->headLink()->appendStylesheet("/js/lib/jquery-datatables/css/demo_table.css");
//			$this->headScript()->appendFile("/js/lib/jquery-datatables/jquery.dataTables.min.js","text/javascript");
//			$this->headScript()->appendFile("/js/lib/jquery-validate/jquery.validate.min.js","text/javascript");
		?>
		<?php //echo $this->jQuery(); ?>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>
	</head>
	<body>
		<div id="header-meta" class="noprint">
			<?php echo $this->partial('header.phtml'); ?>
		</div>

		<div id="actionbar" style="z-index:3;">
			<?php echo $this->partial('actionbar.phtml'); ?>
		</div>

		<div id="footer" class="noprint">
			<?php echo $this->partial('footer.phtml'); ?>
		</div>

		<div id="content">
			<?php echo $this->layout()->content; ?>
		</div>
      	<?php echo $this->flashMessages();?>
	</body>
</html>