<?php echo $this->doctype();?>
<html lang="es">
	<head>
        <title><?php echo _('TAXI DIRECTOR')?></title>
        <meta charset="utf-8">
		<link rel="stylesheet" href="/css/login.css">
	</head>
	<body>
        <header>
        </header>
        <section>
            <?php echo $this->layout()->content;?>
            <article>
                <form method="post" action="<?php $this->url(array('action' => 'login'));?>">
                    <input name="username" id="username" type="text" class="input-text" placeholder="USUSARIO"/>
                    <input name="password" id="password" type="password" class="input-text" placeholder="CLAVE"/>
                    <button id="submit" class="submitBtn" type="submit"  name="submit"><span>INGRESE</span></button>
                    <a href="#" class="button">¿OLVIDASTE TU CLAVE?</a>
                </form>
            </article>
        </section>
    </body>
</html>