<?php echo $this->doctype(); ?>
<html>
	<head>
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<link href="/css/input.css" rel="stylesheet" media="screen" type="text/css" />
		<link href="/css/login.css" rel="stylesheet" media="screen" type="text/css" />
		<script type="text/javascript" src="/js/lib/jquery/jquery.min.js"></script>
	</head>
	<body>
		<div id="wrap">
			<div id="content">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</body>
</html>