<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Pastor.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>

<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _('Filtrar Pastores'));?>
	<?php echo $this->formFilter;?>
	<div id="containerFormFilter">

	</div>
	<br>
	<?php echo $this->tableHeader('pastorHeader', _('Pastores'));?>
	<?php echo $this->tableList('tblPastor');?>
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-pastor", $this->translate('Eliminar'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-pastor", $this->translate('Adicionar'), $this->url(array('action'=>'add')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var pastor = new com.em.Pastor();

	// network
	pastor.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'ds-pastor-entries'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
	    toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre')?>',
		'<?php echo $this->translate('Celular')?>',
		'<?php echo $this->translate('Telf. Fijo')?>',
		'<?php echo $this->translate('Distrito')?>',
		'<?php echo $this->translate('Correo')?>',
		'<?php echo $this->translate('Cedula de Identidad')?>',
		'<?php echo $this->translate('Fecha Creacion')?>',
		'<?php echo $this->translate('Fecha Edicion')?>');
	pastor.setHeaders(headers);
	// configuration of widgets
	pastor.configureTable('#tblPastor', true);

	// CRUD
	pastor.clickToAdd('#create-pastor');
	pastor.clickToUpdate('#tblPastor a[id^=update-pastor-]');
	pastor.clickToDelete('#delete-pastor');
	pastor.configureAuto('input#nameFilter');
});
</script>