<div id="cssmenu" style="width: 10%; float: left;">
    <ul>
        <li><a href='#'><span>Carreras</span></a>
        <ul>
            <li style="background: #83ACFF;"><a id="create-ride" href="<?php echo $this->url(array('action'=>'add'))?>">Nueva</a></li>
            <li style="background: #FFA347;"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'))?>">No Asignada</a></li>
            <li style="background: #FF94B8;"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'))?>">En Espera</a></li>
            <li style="background: #75FF75;"><a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'))?>">En Curso</a></li>
        </ul>
        </li>

        <li><a href='#'><span>Pasajeros</span></a>
        <ul>
            <li style="background: #83ACFF;"><a href='#'>Nuevo</a></li>
            <li style="background: #FFA347;"><a href='#'>Buscar</a></li>
        </ul>
        </li>

        <li><a href='#'><span>Taxis</span></a>
        <ul>
            <li style="background: #83ACFF;"><a href='#'>Sin Carrera</a></li>
            <li style="background: #75FF75;"><a href='#'>En Curso</a></li>
            <li style="background: #FFFF66;"><a href='#'>Apagados</a></li>
            <li style="background: #9999FF;"><a href='#'>Alta/Baja</a></li>
        </ul>
        </li>
    </ul>
</div>