<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Taxi.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>
<style type="text/css">
#map-canvas {
	height: 600px
}

table.zebralist > tbody > tr > td {
 	background-color: #bdd2b4;
}

table.zebralist > thead > tr > th {
	padding: 0px 0px 0px 0px;
}
</style>

<div style="margin:70px 0px;">
    <div style="width: 239px; float: left;">
    <a href="/admin" id="header-taxi">ALTA/BAJA</a>
    <a href="/admin/Taxi/add" id="create-taxi">NUEVO...</a>
        <?php echo $this->tableList('tblTaxi');?>
    </div>

    <div id="map-canvas" style=" width: 90%; right: 0px;">
    </div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true">
</script>

<script type="text/javascript">
	$(document).ready(function() {
	var taxi = new com.em.Taxi();

	// network
	taxi.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'ds-taxi-entries'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>'
	});

	taxi.configureTable('#tblTaxi', true);

	taxi.clickToAdd('#create-taxi');
	taxi.clickToUpdate('#tblTaxi a[id^=update-taxi-]');
	taxi.clickToDelete('#delete-taxi');
});

	var map;

	function initialize() {
		var mapOptions = {center: new google.maps.LatLng(-17.760458, -63.131776),	zoom: 15};
		map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
	}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>