<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Taxi.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>
<style type="text/css">
#map-canvas {
	height: 600px
}
table.zebralist > tbody > tr {
	background-color: #83ACFF;
}

table.zebralist > tbody > tr > td {
	background-color: #83ACFF;
}
</style>

<div style="margin:10px;">
    <div id="cssmenu" style="width: 10%; float: left;">
        <a href="/admin" >Volver</a>
        <?php echo $this->tableList('tblTaxi');?>
    </div>

    <div id="map-canvas" style=" width: 90%; right: 0px;">
    </div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true">
</script>

<script type="text/javascript">
	$(document).ready(function() {
	var taxi = new com.em.Taxi();

	// network
	taxi.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'ds-taxi-entries-without-career'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nuevo')?>');
	//taxi.setHeaders(headers);
	// configuration of widgets
	taxi.configureTable('#tblTaxi', true);

	// CRUD
	taxi.clickToAdd('#create-taxi');
	taxi.clickToUpdate('#tblTaxi a[id^=update-taxi-]');
	taxi.clickToDelete('#delete-taxi');
});

	var map;

	function initialize() {
		var mapOptions = {center: new google.maps.LatLng(-17.760458, -63.131776),	zoom: 15};
		map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
	}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>