<div id="dialog-form" title="<?php echo $this->translate('Adicionar Pasajero'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
	com.em.RideAdd.prototype.dialogButtons = {
		'<?php echo $this->translate('Aceptar'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Ride', 'action'=>'add-save'));?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.RideAdd.prototype.flashError('<?php echo _('El Formulario tiene errores y no se ha guardado');?>', {header: com.em.Alert.ERROR});
						return false;
					}

					return true;
				},

				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.RideAdd.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.phone_duplicate) {
								$("#phone").parent().find('.error').remove();
								$("#phone").parent().append('<label class="error" for="phone" generated="true">'+data.message+'</label>');
								com.em.RideAdd.prototype.flashError('<?php echo _('El Telefono ya existe')?>', {header: com.em.Alert.ERROR});
							} else {
// 								var name = data.messageArray.name;

// 								if (name != undefined) {
// 									$('#name').parent().find('.error').remove();
// 									$('#name').parent().append('<label class="error" for="name" generated="true">'+name.isEmpty+'</label>');
// 								}
							}
// 							com.em.RideAdd.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},

				complete: function(jqXHR, textStatus) {

				},

				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.RideAdd.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		},
		'<?php echo $this->translate('Descartar'); ?>': function() {
			$(this).dialog("close");
		}
	};

	$("#phone").bind('keydown', function(e) {
		if (e.type == 'keydown' && e.which == '13') {
			search();
		}
	});

	function search() {
// 		alert('pepe ds Search');
		this.phone = $("#phone").val();
		$.ajax({
			url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Ride', 'action'=>'ds-search'));?>',
			type: "POST",
			dataType: 'json',
			data: {'phone' : this.phone},
			beforeSend: function(XMLHttpRequest) {
				validator.form();
				if (!validator.valid()) {
					com.em.RideAdd.prototype.flashError('<?php echo _('El Formulario tiene errores y no se ha guardado');?>', {header: com.em.Alert.ERROR});
					return false;
				}

				return true;
			},

			success: function(data, textStatus, XMLHttpRequest) {
				if (data.success) {
					$('#id').val(data.data.id);
					$('#name').val(data.data.name);
					$('#address').val(data.data.address);

					$('#label option').remove();
					$.each(data.addressArray, function(i) {
						$('#label').append($("<option></option>")
							.attr('value', i)
							.text(data.addressArray[i]));
					});
				} else {
					$('#id').val('');
					$('#name').val('');
					$('#address').val('');

					$('#label option').remove();
					com.em.RideAdd.prototype.flashError('<?php echo _('Pasajero no encontrado')?>', {header: com.em.Alert.ERROR});
				}
			},

			complete: function(jqXHR, textStatus) {
			},

			error: function(jqXHR, textStatus, errorThrown) {
				dialogForm.dialog('close');
				com.em.RideAdd.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
			}
		});
    }

	$("#label").change(function () {
		this.labelId = $("#label").val();

		// Sends request by ajax
		$.ajax({
		url: '<?php echo $this->url(array('controller'=>'Ride', 'action'=>'ds-ride-address'));?>',
		type: "POST",
		dataType: 'json',
		data: {'labelId' : this.labelId },
		beforeSend: function(XMLHttpRequest) {
			return true;
		},

		success: function(data, textStatus, XMLHttpRequest) {
			// Removes all options for the select box
			//$('#region option').remove();
			// .each loops through the array
			$.each(data.name, function(i) {
				console.log(data.name);
// 				$('#region').append($("<option></option>")
// 					.attr("value", i)
// 					.text(data.regionsArray[i]));
			});
		},

		complete: function(jqXHR, textStatus) {},

		error: function(jqXHR, textStatus, errorThrown) {}
	    });
	});
</script>