<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/style-menu.css");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Ride.js","text/javascript");?>
<style type="text/css">
#map-canvas {
	height: 500px
}
</style>
<div style="margin:10px;">
<div id="cssmenu" style="width: 10%; float: left;">
       <ul>
            <li><a href='#'><span>Inicio</span></a>
            <li><a href='#'><span>Carreras</span></a>
            <ul>
                <li style="background: #83ACFF;">
                    <a href="/admin/Ride/add" id="create-ride">Nuevo</a>
                </li>
                <li style="background: #FFA347;"><a href="">No Asignada</a></li>
                <li style="background: #FF94B8;"><a href='#'>En Espera</a></li>
                <li style="background: #75FF75;"><a href='#'>En Curso</a></li>
            </ul>
            </li>

            <li><a href='#'><span>Pasajeros</span></a>
            <ul>
                <li style="background: #83ACFF;"><a href='#'>Nuevo</a></li>
                <li style="background: #FFA347;"><a href='#'>Buscar</a></li>
            </ul>
            </li>

            <li><a href='#'><span>Taxis</span></a>
            <ul>
                <li style="background: #83ACFF;"><a href='#'>Sin Carrera</a></li>
                <li style="background: #75FF75;"><a href='#'>En Curso</a></li>
                <li style="background: #FFFF66;"><a href='#'>Apagados</a></li>
                <li style="background: #9999FF;"><a href='#'>Alta/Baja</a></li>
            </ul>
            </li>
        </ul>
    </div>

    <div id="map-canvas" style=" width: 90%; right: 0px;">
</div>
    <div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true">
</script>
<script type="text/javascript">
	$(document).ready(function() {
		 $('#cssmenu > ul > li:has(ul)').addClass("has-sub");

		  $('#cssmenu > ul > li > a').click(function() {
		    var checkElement = $(this).next();

		    $('#cssmenu li').removeClass('active');
		    $(this).closest('li').addClass('active');


		    if((checkElement.is('ul')) && (checkElement.is(':visible'))) {
		      $(this).closest('li').removeClass('active');
		      checkElement.slideUp('normal');
		    }

		    if((checkElement.is('ul')) && (!checkElement.is(':visible'))) {
		      $('#cssmenu ul ul:visible').slideUp('normal');
		      checkElement.slideDown('normal');
		    }

		    if (checkElement.is('ul')) {
		      return false;
		    } else {
		      return true;
		    }
		  });

	var ride = new com.em.Ride();

	// network
	ride.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'ds-ride-entries'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>',
		toAutocompleteLabel : '<?php echo $this->url(array('action'=>'autocomplete-label'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nota'); ?>',
		'<?php echo $this->translate('Descripcion'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	//ride.setHeaders(headers);
	// configuration of widgets
	ride.configureTable('#tblRide', true);

	// CRUD
	ride.clickToAdd('#create-ride');
	ride.clickToUpdate('#tblRide a[id^=update-ride-]');
	ride.clickToDelete('#delete-ride');
	//ride.configureAuto('input#nameFilter');
	ride.configureLabelAuto('input#label');
});

	var map;

	function initialize() {
		var mapOptions = {center: new google.maps.LatLng(-17.760458, -63.131776),	zoom: 15};
		map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
	}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>