<?php $this->headLink()->appendStylesheet($this->baseUrl() . "/css/style-menu.css");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Ride.js","text/javascript");?>
<style type="text/css">
#map-canvas {
	height: 600px
}
table.zebralist > tbody > tr {
	background-color: #75FF75;
}

table.zebralist > tbody > tr > td {
	background-color: #75FF75;
}

</style>
<div style="margin:10px;">
    <div id="cssmenu" style="width: 10%; float: left;">
        <a href="/admin" >Volver</a>
        <?php echo $this->tableList("tblRide");?>
    </div>

    <div id="map-canvas" style=" width: 90%; right: 0px;">
    </div>

    <div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript"
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBADa-A2Jqkq2C4ZlgOdZs98dFE0q00_N0&sensor=true">
</script>
<script type="text/javascript">
	$(document).ready(function() {
	    var ride = new com.em.Ride();

    	// network
	    ride.setUrl({
	        toTable : '<?php echo $this->url(array('action'=>'ds-ride-entries-on-going'))?>',
	        toBase : '<?php echo $this->baseUrl()?>',
	        toUpdate : '<?php echo $this->url(array('action'=>'resume'))?>'
    	});

    	var headers = new Object();
    	headers.headerArray = new Array(
    		'<?php echo $this->translate('En Curso');?>');
    	ride.setHeaders(headers);
    	// configuration of widgets
    	ride.configureTable('#tblRide', true);

    	// CRUD
    	ride.clickToUpdate('#tblRide a[id^=update-ride-]');
    	ride.clickToDelete('#delete-ride');
    });

	var map;

	function initialize() {
		var mapOptions = {center: new google.maps.LatLng(-17.760458, -63.131776),	zoom: 15};
		map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
	}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>