<div id="dialog-form" title="<?php echo $this->translate('Adicionar Pasajero'); ?>" class="header" style="display: none;">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
com.em.PassengerAdd.prototype.setUrl({
	toAutocompleteLabel : '<?php echo $this->url(array('action'=>'autocomplete-label'));?>'
});
com.em.PassengerAdd.prototype.configureLabelAuto('input#label');
	com.em.PassengerAdd.prototype.dialogButtons = {
		'<?php echo $this->translate('Cancelar'); ?>': function() {
			$(this).dialog("close");
		},
		'<?php echo $this->translate('Guardar'); ?>': function() {
			$.ajax({
				url: '<?php echo $this->url(array('module'=>'admin', 'controller'=>'Passenger', 'action'=>'add-save'));?>',
				type: "POST",
				dataType: 'json',
				data: $('#formId').serialize(),
				beforeSend: function(XMLHttpRequest) {
					validator.form();
					if (!validator.valid()) {
						com.em.PassengerAdd.prototype.flashError('<?php echo _('El Formulario tiene errores y no se ha guardado');?>', {header: com.em.Alert.ERROR});
						return false;
					}

					//com.em.Passenger.prototype.processingDisplay(true);
					return true;
				},

				success: function(data, textStatus, XMLHttpRequest) {
					if (textStatus == 'success') {
						if (data.success) {
							dialogForm.dialog('close');
							table.fnDraw();
							com.em.PassengerAdd.prototype.flashSuccess(data.message, {header: com.em.Alert.SUCCESS});
						} else {
							if (data.phone_duplicate) {
								$("#phone").parent().find('.error').remove();
								$("#phone").parent().append('<label class="error" for="phone" generated="true">'+data.message+'</label>');
								com.em.PassengerAdd.prototype.flashError('<?php echo _('El Telefono ya existe')?>', {header: com.em.Alert.ERROR});
							} else {
// 								var name = data.messageArray.name;

// 								if (name != undefined) {
// 									$('#name').parent().find('.error').remove();
// 									$('#name').parent().append('<label class="error" for="name" generated="true">'+name.isEmpty+'</label>');
// 								}
							}
// 							com.em.PassengerAdd.prototype.flashError(data.message, {header: com.em.Alert.ERROR});
						}
					}
				},

				complete: function(jqXHR, textStatus) {
					com.em.PassengerAdd.prototype.processingDisplay(false);
				},

				error: function(jqXHR, textStatus, errorThrown) {
					dialogForm.dialog('close');
					com.em.PassengerAdd.prototype.flashError(errorThrown,{header: com.em.Alert.ERROR});
				}
			});
		}
	};


	$("#label").change(function () {
		this.labelId = $("#label").val();

		// Sends request by ajax
		$.ajax({
		url: '<?php echo $this->url(array('controller'=>'Passenger', 'action'=>'ds-passenger-address'));?>',
		type: "POST",
		dataType: 'json',
		data: {'labelId' : this.labelId },
		beforeSend: function(XMLHttpRequest) {
			return true;
		},

		success: function(data, textStatus, XMLHttpRequest) {
			// Removes all options for the select box
			//$('#region option').remove();
			// .each loops through the array
			$.each(data.name, function(i) {
				console.log(data.name);
// 				$('#region').append($("<option></option>")
// 					.attr("value", i)
// 					.text(data.regionsArray[i]));
			});
		},

		complete: function(jqXHR, textStatus) {},

		error: function(jqXHR, textStatus, errorThrown) {}
	    });
	});
</script>