<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Passenger.js","text/javascript");?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _('Filtrar Pasajeros'));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('passengerHeader', _('Pasajeros'));?>
	<?php echo $this->tableList("tblPassenger");?>
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-passenger", $this->translate('Eliminar'), $this->url(array('action'=>'remove')));?>
		<?php echo $this->buttonAdd("create-passenger", $this->translate('Adicionar'), $this->url(array('action'=>'add')));?>
		<?php echo $this->buttonAdd("search-passenger", $this->translate('Search'), $this->url(array('action'=>'search')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var passenger = new com.em.Passenger();

	// network
	passenger.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>',
		toAutocompleteLabel : '<?php echo $this->url(array('action'=>'autocomplete-label'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre'); ?>',
		'<?php echo $this->translate('Descripcion'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	passenger.setHeaders(headers);
	// configuration of widgets
	passenger.configureTable('#tblPassenger', true);

	// CRUD
	passenger.clickToAdd('#create-passenger');
	passenger.clickToUpdate('#tblPassenger a[id^=update-passenger-]');
	passenger.clickToDelete('#delete-passenger');
	passenger.configureAuto('input#nameFilter');
	passenger.configureLabelAuto('input#label');

	passenger.clickToAdd('#search-passenger');
});
</script>