<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Category.js","text/javascript");?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _('Filtrar Roles'));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('roleHeader', _('Roles'));?>
	<?php echo $this->tableList('tblCategory');?>
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-category", $this->translate('Eliminar'), $this->url(array('action'=>'remove')));?>
		<?php echo $this->buttonAdd("create-category", $this->translate('Adicionar'), $this->url(array('action'=>'add')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var category = new com.em.Category();

	// network
	category.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
		toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre'); ?>',
		'<?php echo $this->translate('Descripcion'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	category.setHeaders(headers);
	// configuration of widgets
	category.configureTable('#tblCategory', true);

	// CRUD
	category.clickToAdd('#create-category');
	category.clickToUpdate('#tblCategory a[id^=update-category-]');
	category.clickToDelete('#delete-category');
	category.configureAuto('input#nameFilter');
});
</script>