<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/jquery.tinymce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/tinymce/jscripts/tiny_mce/tiny_mce.js","text/javascript"); ?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/News.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/HelpTextUpdate.js","text/javascript"); ?>
<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _('Filtrar Noticias'));?>
	<div id="containerFormFilter">
		<?php echo $this->formFilter; ?>
	</div>
	<br>
	<?php echo $this->tableHeader('newsHeader', _('Noticias'));?>
	<?php echo $this->tableList("tblNews");?>
	<div class="buttons right">
		<?php echo $this->buttonRemove('delete-news', $this->translate('Eliminar'), $this->url(array('action'=>'remove')));?>
		<?php echo $this->buttonAdd('create-news2', $this->translate('Adicionar'), $this->url(array('action'=>'add')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
	var news = new com.em.News();

	// network
	news.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Titulo'); ?>',
		'<?php echo $this->translate('Resumen'); ?>',
		'<?php echo $this->translate('Categoria'); ?>',
		'<?php echo $this->translate('Nombre Imagen'); ?>',
		'<?php echo $this->translate('Fecha de Noticia'); ?>',
		'<?php echo $this->translate('Fuente'); ?>',
		'<?php echo $this->translate('Fecha Creacion'); ?>',
		'<?php echo $this->translate('Fecha Edicion'); ?>');
	news.setHeaders(headers);
	// configuration of widgets
	news.configureTable('#tblNews', true);

	// CRUD
	news.clickToAdd('#create-news');
	news.clickToUpdate('#tblNews a[id^=update-news-]');
	news.clickToDelete('#delete-news');
});
</script>