<!-- wrapper-header -->
<!--<div class="wrapper" style="top: -30px;">-->
<div class="wrapper">
	<a href="<?php echo $this->url(array('action'=>'index', 'controller'=>'Index'));?>"><img id="logo" src="/image/logos/Logo_IASD_dist_nuevo_palmar.png" width="600px" height="115px" alt="Nova" style="top: 0px;"/></a>
	<!-- search -->
	<div class="top-search">
		<form  method="get" id="searchform" action="#">
			<div>
				<input type="text" value="Search..." name="s" id="s" onfocus="defaultInput(this)" onblur="clearInput(this)" />
				<input type="submit" id="searchsubmit" value=" " />
			</div>
		</form>
	</div>
	<!-- ENDS search -->
</div>
<!-- ENDS wrapper-header -->