-- #timestamp <20140417094100>

ALTER TABLE `tblTaxi`
	ADD COLUMN `active`		BOOL		NOT NULL DEFAULT 0;

ALTER TABLE `tblTaxi`
	ADD COLUMN `phone` VARCHAR(15) DEFAULT NULL,
	ADD COLUMN `codeactivation` VARCHAR(50) DEFAULT NULL,
	ADD COLUMN `codeuser` VARCHAR(10) DEFAULT NULL
	;

ALTER TABLE `tblTaxi`
	ADD COLUMN `activeimage`	BOOL	NOT NULL DEFAULT 0;
	
ALTER TABLE `tblTaxi`
	ADD COLUMN `dateStatus` DATETIME DEFAULT NULL;

ALTER TABLE `tblRide`
	ADD COLUMN `dateStatus` DATETIME DEFAULT NULL;