<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;
use Model\Taxi;

/**
 * BacktrackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BacktrackRepository extends EntityRepository {

    /**
     * Alias of the table
     * @var string
     */
    private $_alias = 'backtrack';

    /**
     * (non-PHPdoc)
     * @see Doctrine\ORM.EntityRepository::findAll()
     */
    public function findAll() {
    	return $this->findBy(array('state' => TRUE));
    }

    /**
     * @param Taxi $taxi
     * @return array The objects.
     */
    public function findByTaxi(Taxi $taxi) {
    	return $this->findBy(array('state' => TRUE, 'taxiId' => $taxi->getId()));
    }

    /**
     * @param Taxi $taxi
     * @return array The objects.
     */
    public function findLastPositionByTaxi(Taxi $taxi) {
    	return $this->findOneBy(array('state' => TRUE, 'taxiId' => $taxi->getId()), array('id' => 'DESC'));
    }
}