<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;
use Model\Taxi;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository {

    /**
     * Returns the Driver model by Taxi
     * @param Account $account
     * @return Driver
     */
    public function findByTaxi(Taxi $taxi) {
        return  $this->findOneBy(array('state' => TRUE, 'taxiId' => $taxi->getId()));
    }

    /**
     * Verifies if the Identity Card already exist it.
     *
     * @param int $identityCard
     * @return boolean
     */
    public function verifyExistIdentityCard($identityCard) {
    	$object = $this->findOneBy(array('identityCard' => $identityCard, 'state' => TRUE));
    	return $object != NULL ? TRUE : FALSE;
    }

    /**
     * Verifies if the id and identity Card already exist it.
     *
     * @param int $id
     * @param int $identityCard
     */
    public function verifyExistIdAndIdentityCard ($id, $identityCard) {
    	$object = $this->findOneBy(array('id' => $id, 'identityCard' => $identityCard, 'state' => TRUE));
    	return $object != NULL ? TRUE : FALSE;
    }
}