<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;
use Model\Taxi;

/**
 * DriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository {

    /**
     * Returns the Driver model by Taxi
     * @param Account $account
     * @return Driver
     */
    public function findByTaxi(Taxi $taxi) {
        return  $this->findOneBy(array('state' => TRUE, 'taxiId' => $taxi->getId()));
    }
}