<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * OperatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperatorRepository extends EntityRepository
{
}
