<?php

namespace Model\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends EntityRepository
{
}
