<form id="<?php echo $this->element->getAttrib('id') ?>">
<?php echo $this->element->getElement('id')->render()?>
	<table>
		<tbody>
			<tr class="odd" >
				<td><?php echo $this->element->getElement('phone')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('phone')->renderViewHelper()?></td>
				<td><?php echo $this->element->getElement('searchButton')->renderViewHelper()?></td>
			</tr>
			<tr id="rowname" class="even" style="visibility: hidden;">
                <td><?php echo $this->element->getElement('firstName')->renderLabel()?></td>
				<td><?php echo $this->element->getElement('firstName')->renderViewHelper()?></td>
			</tr>
			<tr id="rowlabel" class="even" style="visibility: hidden;">
                <td><?php echo $this->element->getElement('label')->renderLabel() ?></td>
                <td><?php echo $this->element->getElement('label')->renderViewHelper() ?></td>
			</tr>

			<tr id="rowaddress" class="even" style="visibility: hidden;">
                <td><?php echo $this->element->getElement('address')->renderLabel() ?></td>
				<td><?php echo $this->element->getElement('address')->renderViewHelper() ?></td>
			</tr>
		</tbody>
	</table>
</form>