<div id="bottom">
	<!-- wrapper-bottom -->
	<div class="wrapper">
		<div id="bottom-text">2011 Nova all rights reserved. <a href="http://www.luiszuno.com"> Victor.Villca</a> </div>
			<!-- Social -->
			<ul class="social ">
				<li><a href="http://www.facebook.com" class="poshytip  facebook" title="Become a fan"></a></li>
				<li><a href="http://www.twitter.com" class="poshytip twitter" title="Follow our tweets"></a></li>
				<li><a href="http://www.dribbble.com" class="poshytip dribbble" title="View our work"></a></li>
				<li><a href="http://www.addthis.com" class="poshytip addthis" title="Tell everybody"></a></li>
				<li><a href="http://www.vimeo.com" class="poshytip vimeo" title="View our videos"></a></li>
				<li><a href="http://www.youtube.com" class="poshytip youtube" title="View our videos"></a></li>
			</ul>
		<!-- ENDS Social -->
		<div id="to-top" class="poshytip" title="To top"></div>
	</div>
<!-- ENDS wrapper-bottom -->
</div>