<div class="top-meta" style="z-index:2;">
</div>
<div class="bottom-meta noprint" style="z-index:1;">
	<ul class="appMenu functionMenu" id="functionMenuLeft" style="list-style-type: none; list-style-position: initial; list-style-image: initial;">
		<?php
		$firstGroup = $this->navigation()->getContainer(); ?>
		<?php $menus = $firstGroup->getPages(); ?>
		<?php foreach ($menus as $menu) : echo $this->type?>
			<li class="<?php echo $menu->isActive() ? "active" : ''; ?>">
				<a href="<?php echo $menu->getHref();?>"><span><?php echo $this->translate($menu->getLabel()); ?></span></a>
			</li>
		<?php endforeach; ?>
	</ul>
	<div class="clear"></div>
</div>