<!DOCTYPE html>
<html lang="es">
	<head>
        <title><?php echo _('TAXI DIRECTOR s')?></title>
        <meta charset="utf-8">
		<link rel="stylesheet" href="/css/login.css">
	</head>
	<body>
        <header style="background-color: green; width: 200px; height: 100px; margin: 0 auto;">
        </header>
        <section style="margin: 0 auto; background-position: center; width: 500px;">
            <?php echo $this->layout()->content;?>
        </section>
    </body>
</html>