<!DOCTYPE  html>
<html>
	<head>
		<meta charset="utf-8">
		<title>MOB</title>

		<!-- CSS -->
		<?php $this->headLink()->appendStylesheet("/css/style.css");?>
		<?php $this->headLink()->appendStylesheet("/css/social-icons.css");?>
		<!--[if IE 8]>
			<link rel="stylesheet" type="text/css" media="screen" href="/css/ie8-hacks.css" />
		<![endif]-->
		<!-- ENDS CSS -->

				<!-- CRM FONTS -->
		<?php $this->headLink()->appendStylesheet("/css/ubuntu.css");?>

		<!-- JS -->
		<?php //$this->headScript()->appendFile("/js/jquery-1.7.2.min.js","text/javascript");?>
		<?php //$this->headScript()->appendFile("/js/jquery-ui-1.8.13.custom.min.js","text/javascript");?>
		<?php $this->headScript()->appendFile("/js/easing.js");?>
		<?php $this->headScript()->appendFile("/js/jquery.scrollTo-1.4.2-min.js","text/javascript");?>
		<?php $this->headScript()->appendFile("/js/quicksand.js","text/javascript");?>
		<?php $this->headScript()->appendFile("/js/jquery.cycle.all.js","text/javascript");?>

		<?php $this->headLink()->appendStylesheet("/js/jquery-ui/jquery-ui-themes/themes/ui-lightness/jquery-ui.css");?>

		<?php $this->headScript()->appendFile("/js/custom.js","text/javascript");?>
		<!--[if IE]>
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!--[if IE 6]>
			<script type="text/javascript" src="js/DD_belatedPNG.js"></script>
			<script>
				/* EXAMPLE */
				//DD_belatedPNG.fix('*');
			</script>
		<![endif]-->
		<!-- ENDS JS -->

		<!-- Nivo slider -->
		<?php $this->headLink()->appendStylesheet("/css/nivo-slider.css");?>
		<?php $this->headScript()->appendFile("/js/nivo-slider/jquery.nivo.slider.js","text/javascript");?>
		<!-- ENDS Nivo slider -->

		<!-- tabs -->
		<?php $this->headLink()->appendStylesheet("/css/tabs.css");?>
		<?php $this->headScript()->appendFile("/js/tabs.js","text/javascript");?>
		<!-- ENDS tabs -->

		<!-- prettyPhoto -->
		<?php $this->headLink()->appendStylesheet("/js/prettyPhoto/css/prettyPhoto.css");?>
		<?php $this->headScript()->appendFile("/js/prettyPhoto/js/jquery.prettyPhoto.js");?>
		<!-- ENDS prettyPhoto -->

		<!-- superfish -->
		<?php $this->headLink()->appendStylesheet("/css/superfish.css");?>
		<?php $this->headLink()->appendStylesheet("/css/superfish-left.css");?>
		<?php $this->headScript()->appendFile("/js/superfish-1.4.8/js/hoverIntent.js");?>
		<?php $this->headScript()->appendFile("/js/superfish-1.4.8/js/superfish.js");?>
		<?php $this->headScript()->appendFile("/js/superfish-1.4.8/js/supersubs.js");?>
		<!-- ENDS superfish -->

		<!-- poshytip -->
		<?php $this->headLink()->appendStylesheet("/js/poshytip-1.0/src/tip-twitter/tip-twitter.css");?>
		<?php $this->headLink()->appendStylesheet("/js/poshytip-1.0/src/tip-yellowsimple/tip-yellowsimple.css");?>
		<?php $this->headScript()->appendFile("/js/poshytip-1.0/src/jquery.poshytip.min.js");?>
		<!-- ENDS poshytip -->

		<!-- Tweet -->
		<?php $this->headLink()->appendStylesheet("/css/jquery.tweet.css");?>
		<?php $this->headScript()->appendFile("/js/tweet/jquery.tweet.js");?>
		<!-- ENDS Tweet -->

		<!-- Fancybox -->
		<?php $this->headLink()->appendStylesheet("/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.css");?>
		<?php $this->headScript()->appendFile("/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.pack.js");?>
		<!-- ENDS Fancybox -->

		<!-- SKIN -->
		<?php $this->headLink()->appendStylesheet("/skins/plastic/style.css");?>

		<!-- JGROWL -->
		<?php $this->headLink()->appendStylesheet("/js/jgrowl/jquery.jgrowl.css");?>
		<?php $this->headLink()->appendStylesheet("/js/jgrowl/flashnotification.css");?>
		<?php $this->headScript()->appendFile("/js/jgrowl/jquery.jgrowl.js","text/javascript");?>
		<?php $this->headScript()->appendFile("/js/jgrowl/Alert.js","text/javascript");?>
		<?php $this->headScript()->appendFile("/js/jgrowl/FlashMessage.js","text/javascript");?>

		<!-- DATATABLES PLUGIN -->
		<?php $this->headLink()->appendStylesheet("/js/jquery-datatables/css/demo_table.css");?>
		<?php $this->headScript()->appendFile("/js/jquery-datatables/jquery.dataTables.min.js","text/javascript");?>

		<?php $this->headLink()->appendStylesheet("/css/zebralist.css");?>

		<?php $this->headLink()->appendStylesheet("/css/footer.css");?>

		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>
		<?php echo $this->headScript(); ?>

		<style type='text/css'>
			body{
			 background-image:url(/image/mob/fondo-paisaje-ja.jpg);
			}
 		</style>

	</head>

	<body class="">


	<!-- WRAPPER -->
	<div id="wrapper">

		<!-- HEADER -->

		<div id="header" style="background-color: yellow; border-radius: 9px 9px 0px 0px;">
			<a href="#" style="padding-left: 0px;"><img id="logo" src="/image/mob/ministerio-joven-log.png" alt="Ministerio Joven MOB" width="200" height="150"/></a>
<!-- 			<img src="/images/meta/tit1.png" width="750" height="30"> -->
			<!-- Social -->
			<div id="social-holder">
					<div style="display: block; float: right; overflow: hidden; margin-right: 20px;">

						<img src="/image/mob/new-logo-mob.png" width="736" height="111">
					</div>
<!-- 				<ul class="social"> -->

<!-- 					<li><a href="http://www.facebook.com" class="poshytip facebook" title="Become a fan"></a></li> -->
<!-- 					<li><a href="http://www.twitter.com" class="poshytip twitter" title="Follow our tweets"></a></li> -->
<!-- 					<li><a href="http://www.dribbble.com" class="poshytip dribbble" title="View our work"></a></li> -->
<!-- 					<li><a href="http://www.addthis.com" class="poshytip addthis" title="Tell everybody"></a></li> -->
<!-- 					<li><a href="http://www.vimeo.com" class="poshytip vimeo" title="View our videos"></a></li> -->
<!-- 					<li><a href="http://www.youtube.com" class="poshytip youtube" title="View our videos"></a></li> -->
<!-- 				</ul> -->
			</div>
			<!-- ENDS Social -->

			<!-- Navigation -->
			<ul id="nav" class="sf-menu">
				<?php
				$container = $this->navigation()->getContainer();
				$pages = $container->getPages();
				foreach ($pages as $menu):?>
					<?php
					if ($menu->isActive()) {?>
					<li class="current-menu-item"><?php
					} else {?>
					<li><?php }?>
						<a href="<?php echo $menu->getHref();?>"><?php echo $menu->getLabel();?></a>
						<?php if ($menu->count() > 1) {?>
						<ul>
							<?php $submenus = $menu->getPages(); ?>
							<?php foreach ($submenus as $submenu):?>
							<li><a href="<?php echo $submenu->getHref();?>"><span><?php echo $this->translate($submenu->getLabel());?></span></a></li>
							<?php endforeach; ?>
						</ul>
						<?php }?>
					</li>
				<?php endforeach;?>
			</ul>
			<!-- Navigation -->

			<!-- search -->

			<!-- ENDS search -->

			<!-- Breadcrumb-->
			<div id="breadcrumbs">
				<?php echo $this->navigation()->breadcrumbs()->setMinDepth(0)->setLinkLast(TRUE)->setSeparator('');?>
			</div>
			<!-- ENDS Breadcrumb-->

		</div>
		<!-- ENDS HEADER -->

		<!-- MAIN -->
		<div id="main">

			<!-- content -->
			<div id="content">
				<?php echo $this->layout()->content;?>
			</div>
			<!-- ENDS content -->

			<!-- Twitter -->
			<!-- ENDS Twitter -->

		</div>
		<!-- ENDS MAIN -->

		<!-- FOOTER -->
		<div id="footer">

			<!-- footer-cols -->
			<!-- ENDS footer-cols -->

			<!-- Bottom -->
			<div id="bottom">
				© 2014 MISION DEL ORIENTE BOLIVIANO <a href="#" style="color: green;">info@misiondeloriente.com</a>

				<div id="to-top" class="poshytip" title="To top"></div>

			</div>
			<!-- ENDS Bottom -->
		</div>
		<!-- ENDS FOOTER -->

	</div>
	<!-- ENDS WRAPPER -->

	<?php echo $this->flashMessages();?>
	</body>

</html>