<div id="dialog-form" title="<?php echo $this->translate('Adicionar Administrador'); ?>" class="header" style="display: none;">
	<?php echo $this->form;?>
</div>

<script type="text/javascript">
$(document).ready(function() {
	var result = $('#result'),
		load = function (e) {
		e = e.originalEvent;
		e.preventDefault();
		window.loadImage(
			(e.dataTransfer || e.target).files[0],
			function (img) {
				result.children().replaceWith(img);
			},
			{
			maxWidth: result.children().outerWidth(),
			canvas: true
			}
		);
	};

	$('#file-input').change(load);
});

com.em.Administrator.prototype.dialogButtons = {
	'<?php echo $this->translate('Guardar'); ?>': function() {
		$('#formId').submit();
	},

	'<?php echo $this->translate('Cancelar'); ?>': function() {
		$(this).dialog("close");
	}
};
</script>