<?php $this->headScript()->appendFile($this->baseUrl() . "/js/modules/admin/Administrator.js","text/javascript");?>
<?php $this->headScript()->appendFile($this->baseUrl() . "/js/lib/blueimp-Load-Image/load-image.min.js","text/javascript"); ?>

<div style="margin:20px;">
	<?php echo $this->tableHeader('filterHeader', _('Filtrar Administradores'));?>
	<?php echo $this->formFilter;?>
	<div id="containerFormFilter">

	</div>
	<br>
	<?php echo $this->tableHeader('administratorHeader', _('Administradores'));?>
	<?php echo $this->tableList('tblAdministrator');?>
	<div class="buttons right">
		<?php echo $this->buttonRemove("delete-administrator", $this->translate('Eliminar'), $this->url(array('action'=>'delete')));?>
		<?php echo $this->buttonAdd("create-administrator", $this->translate('Adicionar'), $this->url(array('action'=>'add')));?>
	</div>

	<div id="dialog"><!-- Loads ajax dialog form --></div>
</div>
<?php //echo $this->imagelogo;?>
<script type="text/javascript">
	$(document).ready(function() {
	var administrator = new com.em.Administrator();

	// network
	administrator.setUrl({
		toTable : '<?php echo $this->url(array('action'=>'read-items'));?>',
		toBase : '<?php echo $this->baseUrl(); ?>',
		toUpdate : '<?php echo $this->url(array('action'=>'edit')); ?>',
	    toAutocomplete : '<?php echo $this->url(array('action'=>'autocomplete'));?>'
	});

	var headers = new Object();
	headers.headerArray = new Array(
		'<?php echo $this->translate('Nombre')?>',
		'<?php echo $this->translate('Position')?>',
		'<?php echo $this->translate('Celular')?>',
		'<?php echo $this->translate('Telf. Fijo')?>',
		'<?php echo $this->translate('Correo')?>',
		'<?php echo $this->translate('Cedula de Identidad')?>',
		'<?php echo $this->translate('Fecha Creacion')?>',
		'<?php echo $this->translate('Fecha Edicion')?>');
	administrator.setHeaders(headers);
	// configuration of widgets
	administrator.configureTable('#tblAdministrator', true);

	// CRUD
	administrator.clickToAdd('#create-administrator');
	administrator.clickToUpdate('#tblAdministrator a[id^=update-administrator-]');
	administrator.clickToDelete('#delete-administrator');
	administrator.configureAuto('input#nameFilter');
});
</script>